### PR TITLE
Add link to vespa.ai stateless onnx model serving

### PR DESCRIPTION
**Pull request by jobergum**

### CODE REVIEW

**Review by kkraune — APPROVED** [review]

**Comment by prasanthpul** [comment]
thanks. please ensure the DCO check passes and we can merge this

**Comment by jobergum** [comment]
Thanks!  I'm not signing that CLA. 

The DCO signature check is fine, but I'm not signing the CLA which on my part would involve legal review and I'm not scheduling a legal review of your CLA for changing the README.

**Comment by prasanthpul** [comment]
CLA is not required

**Comment by prasanthpul** [comment]
To fix the DCO, please see https://github.com/onnx/tutorials/pull/252/checks?check_run_id=3348125787

**Comment by jobergum** [comment]
That took me some time to sign the correct commits, then merge conflict 😻 

Please review @prasanthpul 🙏 

image

**Review by prasanthpul — APPROVED** [review]

**Comment by prasanthpul** [comment]
Thank you!

**Pull request merged**
